// Bebidas
export const OBTENER_BEBIDAS = 'OBTENER_BEBIDAS';
export const NUEVA_BEBIDA = 'NUEVA_BEBIDA';
export const ACTUALIZAR_BEBIDA = 'ACTUALIZAR_BEBIDA';
export const SELECCIONAR_BEBIDA = 'SELECCIONAR_BEBIDA';
export const ELIMINAR_BEBIDA = 'ELIMINAR_BEBIDA';

// Ordenes
export const OBTENER_ORDENES = 'OBTENER_ORDENES';

// Cortes
export const OBTENER_CORTES = 'OBTENER_CORTES';
export const SELECCIONAR_CORTE = 'SELECCIONAR_CORTE';